site_name: IndexSports
theme:
  name: material
  palette:
    primary: cyan
    accent: cyan
  icon:
    repo: fontawesome/brands/github-alt

nav:
  - Overview: index.md
  - Competitions: competition.md
  - Elements: elements.md

markdown_extensions:
  #  - markdown.extensions.codehilite:
  #      guess_lang: false
  - markdown_include.include:
      base_path: docs
  - admonition
  - extra
  - codehilite

extra_css:
  - assets/styles.css
